import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/header";
import Footer from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "MobileHub - Premium Mobile Store | Latest Smartphones & Accessories",
  description:
    "Discover the latest smartphones, mobile accessories, and exclusive deals at MobileHub. Premium quality, competitive prices, and exceptional customer service.",
  keywords: "mobile phones, smartphones, iPhone, Samsung, Google Pixel, OnePlus, mobile accessories, phone deals",
  authors: [{ name: "MobileHub Team" }],
  openGraph: {
    title: "MobileHub - Premium Mobile Store",
    description: "Your trusted destination for the latest smartphones and mobile technology.",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "MobileHub - Premium Mobile Store",
    description: "Discover the latest smartphones and exclusive deals.",
  },
  robots: {
    index: true,
    follow: true,
  },
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={true} disableTransitionOnChange={false}>
          <Header/>
          {children}
           <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
